### ISSUE TITLE
compilation error of io_uring (lib) since commit 372cdf91274c9817ecb2636ce027e8c64db703fc

### ISSUE THREAD

**Issue by dania83** [pop-os/cosmic-files#955]
Hi
I cannot compile cosmic-files since commit 372cdf91274c9817ecb2636ce027e8c64db703fc. io_uring (lib) failed to compile.

   Compiling lyon v1.0.1====>          ] 536/845: image, cosmic-protocols, ab_glyph, x11-dl(build), wgpu-core, wgpu, zstd-sys(build), cosmic-client-toolkit
   Compiling rust-embed-impl v8.7.0    ] 538/845: image, cosmic-protocols, ab_glyph, glib-sys(build), wgpu-core, wgpu, zstd-sys(build), cosmic-client-toolkit
   Compiling zbus_names v3.0.0         ] 540/845: image, cosmic-protocols, ab_glyph, rust-embed-impl, wgpu-core, wgpu, zstd-sys(build), io-uring
error[E0425]: cannot find value `IORING_OP_FIXED_FD_INSTALL` in module `sys`ust-embed-impl, zbus_names, wgpu-core, wgpu, zstd-sys(build), io-uring
    --> /root/.cargo/git/checkouts/io-uring-20686acfd8eae890/2c9010a/src/opcode.rs:1865:27
     |
1865 |     pub const CODE = sys::IORING_OP_FIXED_FD_INSTALL;
     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `sys`

error[E0425]: cannot find value `IORING_OP_FTRUNCATE` in module `sys`
    --> /root/.cargo/git/checkouts/io-uring-20686acfd8eae890/2c9010a/src/opcode.rs:1890:27
     |
1890 |     pub const CODE = sys::IORING_OP_FTRUNCATE;
     |                           ^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `IORING_OP_FALLOCATE`
     |
    ::: /tmp/work/src/cosmic-files/target/release/build/io-uring-4818ff8e8dce3110/out/sys.rs:1121:1
     |
1121 | pub const IORING_OP_FALLOCATE: io_uring_op = 17;
     | ------------------------------------------------ similarly named constant `IORING_OP_FALLOCATE` defined here

error[E0425]: cannot find value `IORING_RECVSEND_BUNDLE` in module `sys`
    --> /root/.cargo/git/checkouts/io-uring-20686acfd8eae890/2c9010a/src/opcode.rs:1925:28
     |
1925 |         sqe.ioprio |= sys::IORING_RECVSEND_BUNDLE as u16;
     |                            ^^^^^^^^^^^^^^^^^^^^^^ not found in `sys`

error[E0425]: cannot find value `IORING_RECVSEND_BUNDLE` in module `sys`
    --> /root/.cargo/git/checkouts/io-uring-20686acfd8eae890/2c9010a/src/opcode.rs:1960:28
     |
1960 |         sqe.ioprio |= sys::IORING_RECVSEND_BUNDLE as u16;
     |                            ^^^^^^^^^^^^^^^^^^^^^^ not found in `sys`

error[E0425]: cannot find value `IORING_RECVSEND_BUNDLE` in module `sys`
    --> /root/.cargo/git/checkouts/io-uring-20686acfd8eae890/2c9010a/src/opcode.rs:2002:28
     |
2002 |         sqe.ioprio |= sys::IORING_RECVSEND_BUNDLE as u16;
     |                            ^^^^^^^^^^^^^^^^^^^^^^ not found in `sys`

error[E0425]: cannot find value `IORING_FEAT_RECVSEND_BUNDLE` in module `sys`
   --> /root/.cargo/git/checkouts/io-uring-20686acfd8eae890/2c9010a/src/lib.rs:597:32
    |
597 |         self.0.features & sys::IORING_FEAT_RECVSEND_BUNDLE != 0
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `sys`

error[E0609]: no field `install_fd_flags` on type `io_uring_sqe__bindgen_ty_3`
    --> /root/.cargo/git/checkouts/io-uring-20686acfd8eae890/2c9010a/src/opcode.rs:1874:30
     |
1874 |         sqe.__bindgen_anon_3.install_fd_flags = file_flags;
     |                              ^^^^^^^^^^^^^^^^ unknown field
     |
     = note: available fields are: `rw_flags`, `fsync_flags`, `poll_events`, `poll32_events`, `sync_range_flags` ... and 16 others

error[E0560]: struct `io_uring_getevents_arg` has no field named `min_wait_usec`
   --> /root/.cargo/git/checkouts/io-uring-20686acfd8eae890/2c9010a/src/types.rs:242:13
    |
242 |             min_wait_usec: 0,
    |             ^^^^^^^^^^^^^ `io_uring_getevents_arg` does not have this field
    |
    = note: available fields are: `pad`

Some errors have detailed explanations: E0425, E0560, E0609.mic-protocols, zbus_names, wgpu-core, wgpu, zstd-sys(build), softbuffer, io-uring
For more information about an error, try `rustc --explain E0425`.
error: could not compile `io-uring` (lib) due to 8 previous errors
warning: build failed, waiting for other jobs to finish...
error: Recipe `build-debug` failed on line 46 with exit code 101)
=======> ERROR: Building 'cosmic-files.sources1745860456any.cards.tar.xz' failed.

The precedent commit 63176a1e2a942c7d2f22999f93fc963e2f8039c3 works . my version of rustc is 1.85.1

Best regards

Dania

**Comment by dania83** [comment]
Hi

commit 372cdf9 adds ligne
io-uring = { git = "https://github.com/tokio-rs/io-uring.git", rev = "2c9010a3316519e02444f41e536623099af58a84" }
This commit 2c9010a in io-uring is [Update sys.rs to 6.14. Does 6.14 referts to the kernel-headers ? Actually my kernel-headers are 6.7.2

Best regards 
Dania

**Comment by dania83** [comment]
Hi
problem has disappeared after upgrade of kernel-headers from 6.7.2 to 6.14.4

Best regards

Dania
